- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/kordon001/ground_truth/odom"
  gz_topic_name: "/kordon001/ground_truth/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/kordon002/ground_truth/odom"
  gz_topic_name: "/kordon002/ground_truth/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/kordon001/scan"
  gz_topic_name: "/kordon001/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
  frame_id: "kordon001/lidar_link"

- ros_topic_name: "/kordon002/scan"
  gz_topic_name: "/kordon002/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
  frame_id: "kordon002/lidar_link"

- ros_topic_name: "/kordon001/gps/fix"
  gz_topic_name: "/kordon001/gps/fix"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA

- ros_topic_name: "/kordon002/gps/fix"
  gz_topic_name: "/kordon002/gps/fix"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA


# - ros_topic_name: "/kordon001/imu"
#   gz_topic_name: "/kordon001/imu"
#   ros_type_name: "sensor_msgs/msg/Imu"
#   gz_type_name: "gz.msgs.IMU"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/kordon002/imu"
#   gz_topic_name: "/kordon002/imu"
#   ros_type_name: "sensor_msgs/msg/Imu"
#   gz_type_name: "gz.msgs.IMU"
#   direction: GZ_TO_ROS